# Use the official Python image from the Docker Hub
FROM python:3.9-slim

RUN apt-get update && apt-get install -y curl && apt-get clean
# Set the working directory in the container
WORKDIR /app

# Install Flask
RUN pip install Flask

# Copy the Python code directly into the Dockerfile
RUN echo """from flask import Flask, request\n\
import os\n\
\n\
app = Flask(__name__)\n\
\n\
@app.route('/', methods=['GET'])\n\
def greet():\n\
    default_name = os.getenv('NAME', 'Stranger')\n\
    name = request.args.get('name', default_name)\n\
    res = f'''Nice to meet you, {name}!\n''' \n\
    return res\n\
\n\
if __name__ == '__main__':\n\
    app.run(host='0.0.0.0', port=5000)\n""" > /app/app.py


# Make port 5000 available to the world outside this container
EXPOSE 5000

# Define environment variable
# ENV NAME World

# Run the Python app when the container launches
CMD ["python", "app.py"]
