# Use an official Python runtime as a base image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Install Flask
RUN pip install Flask

# Create app.py file
RUN echo "from flask import Flask\nimport os\nimport socket\napp = Flask(__name__)\n\n@app.route('/')\ndef print_host_details():\n    hostname = os.uname().nodename\n    try:\n        host_ip = socket.gethostbyname(hostname)\n    except Exception as e:\n        host_ip = str(e)\n    return f'''Hostname: {hostname} \nIP Address: {host_ip}\n'''\n\nif __name__ == '__main__':\n    app.run(host='0.0.0.0', port=5000)" > app.py

# Make port 5000 available to the world outside this container
EXPOSE 5000

# Define the command to run the Flask app
CMD ["python", "app.py"]
