name: minik8s

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
    # - uses: actions/checkout@v3 
    - name: Set up system env
      run: |
        sudo chmod 777 ./scripts/setup.sh
        sudo ./scripts/setup.sh
      working-directory: /root/minik8s

    - name: Build Production
      run: |
        go build -o ./build/kubectl/kubectl ./cmd/kubectl
        go build -o ./build/apiserver/apiserver ./cmd/apiserver
        go build -o ./build/worker/worker ./cmd/worker
        mkdir -p ~/minik8s
        mkdir -p ~/minik8s/bin
        cp -r ./build ~/minik8s/bin
      working-directory: /root/minik8s

    - name: Run Binaries in Background
      run: |
        ./build/kubectl/kubectl &
        ./build/apiserver/apiserver &
        ./build/worker/worker &
      working-directory: /root/minik8s

    - name: Run Test
      run: | 
        sudo chmod +x ./scripts/tests/test_all.sh
        sudo ./scripts/tests/test_all.sh
      working-directory: /root/minik8s


